# Generated by Django 5.1.6 on 2025-02-27 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_cell_spreadsheet_alter_spreadsheet_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="formula",
        ),
    ]
