# Generated by Django 5.1.6 on 2025-02-28 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_spreadsheetsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpreadsheetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500)),
                (
                    "spreadsheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="api.spreadsheet",
                    ),
                ),
            ],
        ),
    ]
