# Generated by Django 5.1.6 on 2025-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_spreadsheetlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spreadsheetlink",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
